platform :ios, '13.0'
inhibit_all_warnings!

target 'BluetoothChat' do

  pod 'MessageKit'
  pod 'SwiftLint'

end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
